---
- name: Determine Cluster Base Domain for Quay Route
  k8s_info:
    api_version: config.openshift.io/v1
    kind: Ingress
    name: cluster
  register: r_ingress_config

# Example return: CLUSTER_SUBDOMAIN = apps.cluster-84d2.84d2.example.opentlc.com
- name: Store the subdomain
  set_fact:
    CLUSTER_SUBDOMAIN: "{{ r_ingress_config.resources[0].spec.domain }}"

- name: Create Quay Operator NS, Homeroom NS, rolebinding, and secret
  k8s:
    state: present
    definition:  "{{ lookup('template', item ) | from_yaml }}"
  loop:
    - ./templates/quay-ns.yml
    - ./templates/homeroom-ns.yml
    - ./templates/rolebinding.yml
    - ./templates/operatorgroup.yml
    - ./templates/subscription.yml
    - ./templates/secret.yml

- name: Create the homeroom template
  command: oc apply -f https://raw.githubusercontent.com/afouladi7/quay-workshop/master/templates/hosted-workshop-production.json -n homeroom

- name: Deploy the homeroom spawner
  command: oc new-app hosted-workshop-production -n homeroom \
          -p SPAWNER_NAMESPACE=homeroom \
          -p CLUSTER_SUBDOMAIN={{ CLUSTER_SUBDOMAIN }} \
          -p WORKSHOP_NAME=quay-workshop \
          -p CONSOLE_IMAGE=quay.io/openshift/origin-console:4.7 \
          -p WORKSHOP_IMAGE=quay.io/redhatgov/quay-workshop:latest \
          -p CUSTOM_TAB_1=Quay=https://quayecosystem-quay-quay.{{ CLUSTER_SUBDOMAIN }} \
          -p CUSTOM_TAB_2=Webhooks=https://webhook.site


## TODO's
# - Resolve the one user per cluster piece with RHPDS using the GUID manager
#     - Have to take this up with rhpds-help@redhat.com
# - Ensure clusters are using smallest cluster footprint size available in rhpds catalog
#     - Have to take this up with rhpds-help@redhat.com
# - Cleanup and finish lab content guide
#   - Lab navigation is referencing absolute github links
#   - Explain the groupings box in the developer console (tags)
#   - Remove first page (instructor notes)
#   - Add steps to monitor the rollout of quay object
# - Quay route in the console is not happy
# - Move oc patch under pic of finished quay, make user wait for everything to be up before running
# - Tell user to wait for quay image to replace


# Leave this as the last task in the playbook.
# --------------------------------------------
- name: workload tasks complete
  debug:
    msg: "Workload Tasks completed successfully."
  when: not silent|bool